INSERT INTO users (firstname, surname) VALUES
('Nyah', 'Dicki'),
('Leone', 'Paucek'),
('Kristofer', 'Herman'),
('Ruthe', 'Sauer'),
('Alyce', 'Hills'),
('Rosamond', 'Armstrong'),
('Dayne', 'Kunze'),
('Marion', 'Trantow'),
('Ashleigh', 'Nicolas'),
('Earl', 'Raynor'),
('Lilliana', 'Bernhard'),
('Leonardo', 'Kuhn'),
('Joan', 'Pfannerstill'),
('Rafaela', 'Hyatt'),
('Jaleel', 'Kozey'),
('Rosalee', 'Schowalter'),
('Clark', 'Considine'),
('Ephraim', 'Romaguera'),
('Parker', 'Johnson'),
('Boris', 'Gutmann'),
('Josh', 'Grady'),
('Katelyn', 'Waelchi'),
('Judson', 'Hills'),
('Dorris', 'Borer'),
('Albin', 'Lebsack'),
('Callie', 'Smitham'),
('Ike', 'Crooks'),
('Adaline', 'Olson'),
('Leslie', 'Kuphal'),
('Destiny', 'Lindgren'),
('Phoebe', 'Larson'),
('Sophie', 'Kemmer'),
('Vada', 'Crist'),
('Coralie', 'Bashirian'),
('Therese', 'Fisher'),
('Leanna', 'Barton'),
('Karina', 'Mohr'),
('Eulah', 'Hyatt'),
('Johathan', 'Doyle'),
('Jermaine', 'Hamill'),
('Christian', 'Shields'),
('Twila', 'Bechtelar'),
('Kamren', 'Howe'),
('Leonie', 'Huel'),
('Katelyn', 'Jast'),
('Clement', 'Ondricka'),
('Jamil', 'Kemmer'),
('Monica', 'Schowalter'),
('Andreanne', 'Larkin'),
('Stanley', 'Brakus'),
('Christine', 'Willms'),
('Lewis', 'Schaefer'),
('Thelma', 'Luettgen'),
('Nova', 'Emmerich'),
('Amos', 'Kunze'),
('Clement', 'Rosenbaum'),
('Nicolette', 'Hodkiewicz'),
('Garett', 'Ebert'),
('Billie', 'Crist'),
('Christiana', 'Mueller'),
('Evangeline', 'Gutkowski'),
('Daphne', 'Runte'),
('Noemie', 'McGlynn'),
('Walter', 'Robel'),
('Tristian', 'Parisian'),
('Wallace', 'Stamm'),
('Jerrod', 'McCullough'),
('Lisa', 'Price'),
('Zita', 'Carter'),
('Annette', 'Lind'),
('Bradly', 'Lubowitz'),
('Kendra', 'Muller'),
('Carlie', 'Murazik'),
('Thaddeus', 'Brown'),
('Kathryne', 'Kris'),
('Elenora', 'Kirlin'),
('Bartholome', 'McGlynn'),
('Jesus', 'Koss'),
('Jailyn', 'Bashirian'),
('Gertrude', 'Fritsch'),
('Allan', 'Jaskolski'),
('Vada', 'Hammes'),
('Fredrick', 'Medhurst'),
('Callie', 'Kassulke'),
('Zena', 'Conn'),
('Laverne', 'Kassulke'),
('Janice', 'Wisoky'),
('Vernon', 'Miller'),
('Percival', 'Kautzer'),
('Merritt', 'Bogan'),
('Reid', 'Cassin'),
('Darby', 'Daugherty'),
('Jarod', 'Donnelly'),
('Edward', 'Hayes'),
('Aiden', 'Mraz'),
('Destini', 'Upton'),
('Kiel', 'Murazik'),
('Norma', 'Renner'),
('Tess', 'Schroeder'),
('Margarette', 'Donnelly');

INSERT INTO courses (description) VALUES
('Introduction to Psychology'),
('Principles of Marketing'),
('Data Structures and Algorithms'),
('Financial Accounting'),
('Organic Chemistry'),
('World History'),
('Calculus I'),
('Business Ethics'),
('Introduction to Sociology'),
('Microeconomics'),
('Human Anatomy'),
('Artificial Intelligence'),
('Graphic Design Basics'),
('Environmental Science'),
('Physics I'),
('Creative Writing'),
('Project Management'),
('Political Science'),
('Philosophy of Mind'),
('Software Engineering'),
('Biostatistics'),
('Molecular Biology'),
('Digital Marketing'),
('Entrepreneurship'),
('Operations Management'),
('Civil Engineering'),
('Introduction to Programming'),
('Econometrics'),
('Database Systems'),
('Strategic Management');

INSERT INTO enrollments (UserID, CourseID, CompletionStatus) VALUES
(48, 13, 'not started'),
(100, 20, 'not started'),
(3, 2, 'completed'),
(30, 16, 'completed'),
(7, 19, 'completed'),
(38, 17, 'completed'),
(14, 1, 'completed'),
(5, 9, 'completed'),
(13, 2, 'in progress'),
(21, 22, 'completed'),
(11, 6, 'completed'),
(30, 26, 'in progress'),
(49, 30, 'in progress'),
(85, 6, 'completed'),
(96, 20, 'completed'),
(68, 11, 'completed'),
(26, 4, 'completed'),
(89, 26, 'in progress'),
(11, 27, 'in progress'),
(82, 9, 'in progress'),
(30, 8, 'in progress'),
(48, 13, 'completed'),
(21, 12, 'not started'),
(52, 13, 'in progress'),
(14, 23, 'in progress'),
(72, 4, 'in progress'),
(15, 19, 'not started'),
(95, 17, 'in progress'),
(35, 11, 'not started'),
(39, 9, 'not started'),
(36, 11, 'in progress'),
(3, 16, 'not started'),
(78, 12, 'completed'),
(14, 2, 'not started'),
(29, 27, 'in progress'),
(87, 13, 'in progress'),
(84, 8, 'in progress'),
(89, 22, 'in progress'),
(1, 19, 'in progress'),
(37, 27, 'in progress'),
(13, 17, 'in progress'),
(94, 28, 'in progress'),
(49, 23, 'in progress'),
(20, 6, 'completed'),
(26, 19, 'not started'),
(94, 11, 'not started'),
(68, 20, 'completed'),
(73, 21, 'in progress'),
(19, 28, 'completed'),
(93, 9, 'completed'),
(46, 12, 'in progress'),
(9, 19, 'not started'),
(97, 7, 'not started'),
(85, 20, 'in progress'),
(43, 19, 'not started'),
(85, 29, 'completed'),
(37, 25, 'not started'),
(26, 10, 'completed'),
(96, 14, 'completed'),
(96, 29, 'in progress'),
(28, 6, 'completed'),
(39, 5, 'completed'),
(11, 3, 'in progress'),
(79, 24, 'not started'),
(94, 3, 'completed'),
(36, 10, 'completed'),
(57, 16, 'completed'),
(82, 8, 'in progress'),
(93, 11, 'not started'),
(54, 1, 'not started'),
(13, 6, 'not started'),
(63, 16, 'not started'),
(95, 6, 'not started'),
(52, 21, 'completed'),
(47, 17, 'in progress'),
(54, 19, 'in progress'),
(95, 28, 'completed'),
(19, 26, 'completed'),
(43, 21, 'in progress'),
(36, 17, 'in progress'),
(84, 11, 'in progress'),
(69, 15, 'completed'),
(95, 10, 'not started'),
(52, 9, 'not started'),
(99, 2, 'not started'),
(58, 3, 'in progress'),
(38, 27, 'not started'),
(62, 17, 'in progress'),
(80, 2, 'in progress'),
(62, 25, 'not started'),
(65, 29, 'completed'),
(12, 29, 'completed'),
(83, 21, 'not started'),
(98, 28, 'not started'),
(63, 11, 'not started'),
(17, 28, 'in progress'),
(97, 22, 'not started'),
(33, 4, 'in progress'),
(95, 13, 'in progress'),
(33, 6, 'not started');
